// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjToyjS_Vr8Bfo3k08lTGAPF6DbesKk30',
    appId: '1:407829922429:web:bfb3b68aa2b0f0a6fd6714',
    messagingSenderId: '407829922429',
    projectId: 'signbridge-3bfb3',
    authDomain: 'signbridge-3bfb3.firebaseapp.com',
    storageBucket: 'signbridge-3bfb3.firebasestorage.app',
    measurementId: 'G-1CR7FMK5HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__Gc2fk1V2kz8o_dY35F-ufu7BQMhcjA',
    appId: '1:407829922429:android:fc5961384d96ba18fd6714',
    messagingSenderId: '407829922429',
    projectId: 'signbridge-3bfb3',
    storageBucket: 'signbridge-3bfb3.firebasestorage.app',
  );
}
