// TranslationMessage
// ─────────────────────────────────────────────────────────────
// THE single AI output format used across the entire system:
//   • AI services emit it
//   • TranslationController routes it
//   • UI overlays render it
//   • DataChannel serializes it (text-only payload)
//   • Hive persists it
//
// DO NOT introduce a different shape anywhere. One source of truth.

import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'translation_message.g.dart'; // generated by build_runner

@HiveType(typeId: 0)
class TranslationMessage extends HiveObject {
  /// Unique id (used for de-duplication when sync'd via DataChannel).
  @HiveField(0)
  final String id;

  /// Recognized / translated text.
  @HiveField(1)
  final String text;

  /// "gesture" or "speech".
  @HiveField(2)
  final String source;

  /// "en" or "sw".
  @HiveField(3)
  final String language;

  /// Optional GIF mapping (null when no asset matches).
  @HiveField(4)
  final String? gifKey;

  /// ISO-8601 string per architecture spec.
  @HiveField(5)
  final String timestamp;

  /// True if this message originated from the remote peer (via DataChannel).
  /// Not serialized over the wire; used only for local rendering.
  @HiveField(6)
  final bool fromPeer;

  TranslationMessage({
    String? id,
    required this.text,
    required this.source,
    required this.language,
    this.gifKey,
    String? timestamp,
    this.fromPeer = false,
  })  : id = id ?? const Uuid().v4(),
        timestamp = timestamp ?? DateTime.now().toUtc().toIso8601String();

  // ── Serialization (for DataChannel JSON) ──
  Map<String, dynamic> toJson() => {
        'id': id,
        'text': text,
        'source': source,
        'language': language,
        'gifKey': gifKey,
        'timestamp': timestamp,
      };

  factory TranslationMessage.fromJson(Map<String, dynamic> j) =>
      TranslationMessage(
        id: j['id'] as String?,
        text: j['text'] as String? ?? '',
        source: j['source'] as String? ?? 'speech',
        language: j['language'] as String? ?? 'en',
        gifKey: j['gifKey'] as String?,
        timestamp: j['timestamp'] as String?,
        fromPeer: true, // anything received from JSON came from peer
      );

  TranslationMessage copyWith({String? gifKey, bool? fromPeer}) =>
      TranslationMessage(
        id: id,
        text: text,
        source: source,
        language: language,
        gifKey: gifKey ?? this.gifKey,
        timestamp: timestamp,
        fromPeer: fromPeer ?? this.fromPeer,
      );
}